### ISSUE TITLE
Clean command for some/all env

### ISSUE THREAD

**Issue by ghostlytalamaur** [svetlyak40wt/dotfiler#16]

**Comment by svetlyak40wt** [comment]
Please, add more details here.

**Comment by ghostlytalamaur** [comment]
Mark it closed. I found `.created-links` file. In this case i can run
```rm -rf `cat ./.created-links | awk '{print $3}'` ```
for remove all links to dotfiller env.
It may be useful if i move ~/.dotfiller into another dir. 
Thanks.

**Comment by svetlyak40wt** [comment]
There is a mistake in your script, to remove symlinks, you need `awk '{print $1}'`.
