### ISSUE TITLE
dotfiler ignores .gitignore_global

### ISSUE THREAD

**Issue by drzel** [svetlyak40wt/dotfiler#9]
This is a dotfile that I'd like to include in my dotfile repo, but it's ignored for some reason..

**Comment by svetlyak40wt** [comment]
Probably, that is because `.gitignore` is ignored in this code: https://github.com/drzel/dotfiler/blob/35b2b74a9126520dff6fd9e6f4088c112bc33f96/bin/lib/dot/core.py#L139

Try to remove `.gitignore` temprorary and see if it will help. If it is, then we'll think how to workaround this problem.

**Comment by drzel** [comment]
I've removed the .gitignore but the issue persists.
I don't really know python but I can't understand from your code why ignoring .gitignore would also ignore .gitignore_global...
Date: Thu, 27 Aug 2015 05:15:57 -0700

**Comment by jawshooah** [comment]
> I can't understand from your code why ignoring .gitignore would also ignore .gitignore_global

Because the string `.gitignore_global` contains a match for the regex.

```python
>>> regex = re.compile('.gitignore')
>>> regex.match('.gitignore_global')
<_sre.SRE_Match object at 0x10b66c4a8>
```

**Comment by drzel** [comment]
Pull request submitted. (:

Date: Thu, 27 Aug 2015 21:17:20 -0700

**Comment by svetlyak40wt** [comment]
Pull request was merged. Thank you, guys!
